<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
======================================================================
	FGDC CSDGM Entity Attribute to ISO 19110 

	initial revisions: 2013, Earth Data Analysis Center
	
	This is based on the ea2fc.xslt provided by NOAA's National Coastal Data 
	Development Center (NCDDC). See the NCDDC version for more information regarding previous revisions:
	
		http://www.ncddc.noaa.gov/metadata-standards/metadata-xml/

	Most of the modifications made to the original XSLT involve refactoring to include templates for
	elements such as contacts and citations, to replace for-loops with more explicit existence checks, 
	and to replace code-generated variable names and other structures to create a more readable transform. 
	We have paid particular attention to updates for vector datasets. See the ea2fc revision for more information.
	
	Note also that, while we have tested this against a variety of FGDC xml, the transformation 
	may still contain gaps in its coverage. 

	Notes:
		- The resulting XML from this transform can be validated within a software application such as 
		  Oxygen, but it fails to validate from the stricter pParse (Apache Xerces). When using pParse,
		  the validation fails as it traverses the schema from the gfc to the gmd - once it hits the CI_Citation
		  element, the validator expects an MI/MD record and fails to recognize the FC_FeatureCatalogue. 
		- This will not function correctly on its own; at a minimum, it relies on the contact template
		  from the MI transformation.
		
	License: 
		The MIT License (MIT)

		Copyright (c) 2013 Earth Data Analysis Center
		
		Permission is hereby granted, free of charge, to any person obtaining a copy
		of this software and associated documentation files (the "Software"), to deal
		in the Software without restriction, including without limitation the rights
		to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
		copies of the Software, and to permit persons to whom the Software is
		furnished to do so, subject to the following conditions:
		
		The above copyright notice and this permission notice shall be included in
		all copies or substantial portions of the Software.
		
		THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
		IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
		FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
		AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
		LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
		OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
		THE SOFTWARE.

-->
<!-- 
	ORIGINAL SOURCE: FGDC CSDGM to ISO 19115-2 Transform using XPath 2.0 June 2012
	
	This is the XML Style sheet that transforms metadata conforming to the Entity and Attribute Section from the Content Standards for Digital Geospatial Metadata 
	 of the Federal Geographic Data Committee June 1998 FGDC-STD-001-1998 version to the ISO 19110.  This stylesheet can be applied to FGDC CSDGM XML that
	 contains the entity and attribute section, with detailed information,  to generate ISO 19110 feature catalog XML. This stylesheet should only be applied if there is 
	 an Entity and Attribute section within the FGDC CSDGM XML file. 

	 This file was generated by Altova MapForce 2009sp1

	 Authors:
	     This is the result of a collaboration of the Metadata Transform Working Group. For further information, please contact NOAA's National Coastal Data 
	     Development Center (NCDDC).
			National Coastal Data Development Center
			Toll Free: 866.732.2382
			E-mail: ncddcmetadata@noaa.gov

	 Distribution liability:
		 NOAA makes no warranty regarding these data, expressed or implied, nor does the fact of distribution constitute such a warranty. NOAA, NESDIS, 
		 NODC and NCDDC cannot assume liability for any damages caused by any errors or omissions in these data, nor as a result of the failure of these data 
		 to function on a particular system. These files were developed for opensource uses.
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gfc="http://www.isotc211.org/2005/gfc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:grp="http://www.altova.com/Mapforce/grouping" exclude-result-prefixes="fn grp xs xsi xsl" xmlns="http://www.isotc211.org/2005/gfc">
	<xsl:output method="xml" encoding="ISO-8859-1" indent="yes"/>
    
    <!-- need the mode for the mi + fc transform (this also starts from the root node, needs a citation/contact outside of eainfo) -->
	<xsl:template match="/metadata" mode="fc">
		<gfc:FC_FeatureCatalogue id="FC001" uuid="{fn:tokenize(fn:substring-before(fn:base-uri(.), '.xml'), '/')[last()]}"
			xsi:schemaLocation="http://www.isotc211.org/2005/gfc http://www.isotc211.org/2005/gfc/gfc.xsd">

			<gmx:name>
				<gco:CharacterString>
					<xsl:value-of select="fn:normalize-space(fn:concat('Feature Catalogue for ', idinfo/citation/citeinfo/title))"/>
				</gco:CharacterString>
			</gmx:name>
			<gmx:scope gco:nilReason="unknown"/>
			<gmx:versionNumber  gco:nilReason="unknown"/>
			<gmx:versionDate gco:nilReason="unknown"/>
			<gmx:language>
				<gco:CharacterString>eng; US</gco:CharacterString>
			</gmx:language>
			<gmx:characterSet>
				<gmd:MD_CharacterSetCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_CharacterSetCode"
					codeListValue="utf8"/>
			</gmx:characterSet>
			<gfc:producer>
				<xsl:apply-templates select="metainfo/metc/cntinfo" >
					<xsl:with-param name="rolecode" select="'resourceProvider'"/>
				</xsl:apply-templates>				
			</gfc:producer>
			<gfc:featureType>
				<gfc:FC_FeatureType>
					<xsl:for-each select="eainfo/detailed/enttyp">
						<gfc:typeName>
							<gco:LocalName>
								<xsl:value-of select="fn:normalize-space(enttypl)"/>
							</gco:LocalName>
						</gfc:typeName>
						<gfc:definition>
							<gco:CharacterString>
								<xsl:value-of select="fn:normalize-space(enttypl)"/>
							</gco:CharacterString>
						</gfc:definition>
					</xsl:for-each>
					<gfc:isAbstract>
						<gco:Boolean>false</gco:Boolean>
					</gfc:isAbstract>
					<!-- TODO: at some point, this may need to be modified for multiple refs? and probably point to the uuid instead -->
					<gfc:featureCatalogue uuidref="FC001"/>
					
					<!-- run all of the attributes -->
					<xsl:for-each select="eainfo/detailed/attr">
						<gfc:carrierOfCharacteristics>
							<gfc:FC_FeatureAttribute>
								<xsl:if test="attrdomv/rdom">
									<gfc:constrainedBy>
										<gfc:FC_Constraint>
											<gfc:description>
												<xsl:variable name="max">
													<xsl:choose>
														<xsl:when test="attrdomv/rdom/rdommax">
															<xsl:value-of select="fn:concat('Range Domain Max: ', attrdomv/rdom/rdommax)"/>
														</xsl:when>
													</xsl:choose>
												</xsl:variable>
												<xsl:variable name="min">
													<xsl:choose>
														<xsl:when test="attrdomv/rdom/rdommin">
															<xsl:value-of select="fn:concat('Range Domain Min: ', attrdomv/rdom/rdommin)"/>
														</xsl:when>
													</xsl:choose>
												</xsl:variable>
												<xsl:variable name="res">
													<xsl:choose>
														<xsl:when test="attrdomv/rdom/attrmres">
															<xsl:value-of select="fn:concat('Smallest unit increment: ', attrdomv/rdom/attrmres)"/>
														</xsl:when>
													</xsl:choose>
												</xsl:variable>
												<gco:CharacterString>
													<xsl:value-of select="$max[text() != ''] | $min[text() != ''] | $res[text() != '']" separator=" | "/>
												</gco:CharacterString>
											</gfc:description>
										</gfc:FC_Constraint>
									</gfc:constrainedBy>
								</xsl:if>
								<gfc:memberName>
									<gco:LocalName>
										<xsl:value-of select="fn:normalize-space(attrlabl)"/>
									</gco:LocalName>
								</gfc:memberName>
								<gfc:definition>
									<gco:CharacterString>
										<xsl:value-of select="fn:normalize-space(attrdef)"/>
									</gco:CharacterString>
								</gfc:definition>
								<gfc:cardinality gco:nilReason="unknown"/>
								<gfc:definitionReference>
									<gfc:FC_DefinitionReference>
										<gfc:definitionSource>
											<gfc:FC_DefinitionSource>
												<gfc:source>
													<gmd:CI_Citation>
														<gmd:title gco:nilReason="inapplicable"/>
														<gmd:date gco:nilReason="unknown"/>
														<gmd:citedResponsibleParty>
															<gmd:CI_ResponsibleParty>
																<gmd:organisationName>
																	<gco:CharacterString>
																		<xsl:value-of select="fn:normalize-space(attrdefs)"/>
																	</gco:CharacterString>
																</gmd:organisationName>
																<gmd:role>
																	<gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode"
																		codeListValue="resourceProvider"/>
																</gmd:role>
															</gmd:CI_ResponsibleParty>
														</gmd:citedResponsibleParty>
													</gmd:CI_Citation>
												</gfc:source>
											</gfc:FC_DefinitionSource>
										</gfc:definitionSource>
									</gfc:FC_DefinitionReference>
								</gfc:definitionReference>
								
								<xsl:if test="attrdomv/rdom">
									<gfc:valueMeasurementUnit>
										<gml:BaseUnit gml:id="{fn:concat('baseUnit_', generate-id())}">
											<gml:identifier codeSpace="{attrdomv/rdom/attrunit}" />
											<!-- can't be gco:nilReason here, that isn't valid -->
											<gml:unitsSystem nilReason="unknown"/>
										</gml:BaseUnit>
									</gfc:valueMeasurementUnit>
								</xsl:if>
								
								<xsl:for-each select="attrdomv/edom">
									<gfc:listedValue>
										<gfc:FC_ListedValue>
											<gfc:label>
												<gco:CharacterString>
													<xsl:value-of select="fn:normalize-space(edomv)"/>
												</gco:CharacterString>
											</gfc:label>
											<gfc:definition>
												<gco:CharacterString>
													<xsl:value-of select="fn:normalize-space(edomvd)"/>
												</gco:CharacterString>
											</gfc:definition>
											<gfc:definitionReference>
												<gfc:FC_DefinitionReference>
													<gfc:definitionSource>
														<gfc:FC_DefinitionSource>
															<gfc:source>
																<gmd:CI_Citation>
																	<gmd:title gco:nilReason="unknown"/>
																	<gmd:date gco:nilReason="unknown"/>
																	<gmd:citedResponsibleParty>
																		<gmd:CI_ResponsibleParty>
																			<gmd:organisationName>
																				<gco:CharacterString>
																					<xsl:value-of select="fn:normalize-space(edomvds)"/>
																				</gco:CharacterString>
																			</gmd:organisationName>
																			<gmd:role>
																				<gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode"
																					codeListValue="resourceProvider"/>
																			</gmd:role>
																		</gmd:CI_ResponsibleParty>
																	</gmd:citedResponsibleParty>
																</gmd:CI_Citation>
															</gfc:source>
														</gfc:FC_DefinitionSource>
													</gfc:definitionSource>
												</gfc:FC_DefinitionReference>
											</gfc:definitionReference>
											
										</gfc:FC_ListedValue>
									</gfc:listedValue>
								</xsl:for-each>
								<!--
									2012-12-12 soren scott
									add the UDOM back in as per jacki
									
									I originally mapped udom to here:  gfc:FC_FeatureCatalogue, gfc:featureType, gfc:FC_FeatureType, gfc:carrierOfCharacteristics, gfc:FC_FeatureAttribute, 
									gfc:listedValue, gfc:FC_ListedValue, gfc:definition  because that worked for most of "our" usage of the udom element. Because udom is a free text "other" field, 
									it was hard to determine the location of the information in other's metadata and how they used the udom field. I removed it for the broader community transforms 
									but if the information in your udom elements should be mapped there then do so. 
								-->
								<!-- REMOVED - this isn't valid (incomplete element) and is probably not the right structure for UDOM anyway -->
								<!--<xsl:for-each select="attrdomv/udom">
									<gfc:listedValue>
										<gfc:FC_ListedValue>
											<gfc:definition>
												<gco:CharacterString>
													<xsl:value-of select="fn:normalize-space(xs:string(.))"/>
												</gco:CharacterString>
											</gfc:definition>
										</gfc:FC_ListedValue>
									</gfc:listedValue>
									</xsl:for-each>-->
								
								<!-- so let's try this which at least validates -->
								<xsl:if test="attrdomv/udom">
									<gfc:valueType>
										<gco:TypeName>
											<gco:aName>
												<gco:CharacterString>
													<xsl:value-of select="fn:normalize-space(attrdomv/udom)"/>
												</gco:CharacterString>
											</gco:aName>
										</gco:TypeName>
									</gfc:valueType>
								</xsl:if>
								<!-- end udom change -->
								
								<xsl:for-each select="attrdomv/codesetd">
									<gfc:listedValue>
										<gfc:FC_ListedValue>
											<gfc:label>
												<gco:CharacterString>
													<xsl:value-of select="fn:normalize-space(codesetn)"/>
												</gco:CharacterString>
											</gfc:label>
											<gfc:definitionReference>
												<gfc:FC_DefinitionReference>
													<gfc:definitionSource>
														<gfc:FC_DefinitionSource>
															<gfc:source>
																<gmd:CI_Citation>
																	<gmd:title gco:nilReason="unknown"/>
																	<gmd:date gco:nilReason="unknown"/>
																	<gmd:citedResponsibleParty>
																		<gmd:CI_ResponsibleParty>
																			<gmd:organisationName>
																				<gco:CharacterString>
																					<xsl:value-of select="fn:normalize-space(codesets)"/>
																				</gco:CharacterString>
																			</gmd:organisationName>
																			<gmd:role>
																				<gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode"
																					codeListValue="resourceProvider"/>
																			</gmd:role>
																		</gmd:CI_ResponsibleParty>
																	</gmd:citedResponsibleParty>
																</gmd:CI_Citation>
															</gfc:source>
														</gfc:FC_DefinitionSource>
													</gfc:definitionSource>
												</gfc:FC_DefinitionReference>
											</gfc:definitionReference>
										</gfc:FC_ListedValue>
									</gfc:listedValue>
								</xsl:for-each>
							</gfc:FC_FeatureAttribute>
						</gfc:carrierOfCharacteristics>
					</xsl:for-each>
				</gfc:FC_FeatureType>
			</gfc:featureType>
			<!-- to include the entity source definition (enttypds) -->
			<!-- TODO: revise for multiple enttyp elements (if possible, but this is outside the larger group so it will be difficult to connect it to the right enttyp parent) -->
			<xsl:if test="eainfo/detailed/enttyp/enttypds">
				<gfc:definitionSource>
					<gfc:FC_DefinitionSource>
						<gfc:source>
							<gmd:CI_Citation>
								<gmd:title gco:nilReason="inapplicable"/>
								<gmd:date gco:nilReason="unknown"/>
								<gmd:citedResponsibleParty>
									<gmd:CI_ResponsibleParty>
										<gmd:organisationName>
											<gco:CharacterString>
												<xsl:value-of select="eainfo/detailed/enttyp/enttypds[1]"/>
											</gco:CharacterString>
										</gmd:organisationName>
										<gmd:role>
											<gmd:CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode"
												codeListValue="resourceProvider"/>
										</gmd:role>
									</gmd:CI_ResponsibleParty>
								</gmd:citedResponsibleParty>
							</gmd:CI_Citation>
						</gfc:source>
					</gfc:FC_DefinitionSource>
				</gfc:definitionSource>
			</xsl:if>
		</gfc:FC_FeatureCatalogue>
	</xsl:template>
</xsl:stylesheet>
